export const perfumeData = [
    { id: 2, name: "40 KNOTS", brand: "XERJOFF" },
    { id: 4, name: "212 HERO", brand: "CAROLINA HERRERA" },
    { id: 6, name: "212 MEN NYC", brand: "CAROLINA HERRERA" },
    { id: 7, name: "212 SEXY MAN", brand: "CAROLINA HERRERA" },
    { id: 9, name: "212 VIP BLACK", brand: "CAROLINA HERRERA" },
    { id: 11, name: "212 VIP MEN", brand: "CAROLINA HERRERA" },
    { id: 12, name: "212 VIP ROSE", brand: "CAROLINA HERRERA" },
    { id: 13, name: "ACCENTO", brand: "SOSPIRO" },
    { id: 14, name: "ACQUA DI GIO", brand: "GIORGIO ARMANI" },
    { id: 15, name: "ACQUA DI GIOIA", brand: "GIORGIO ARMANI" },
    { id: 16, name: "ACQUA DI GIO PROFUMO", brand: "GIORGIO ARMANI" },
    { id: 18, name: "ACQUA ESSENZIALE", brand: "SALVATORE FERRAGAMO" },
    { id: 24, name: "24 GOLD", brand: "SCENT STORY" },
    { id: 20, name: "AFTERNOON SWIM", brand: "LOUIS VUITTON" },
    { id: 23, name: "ALEXANDRIA II", brand: "XERJOFF" },
    { id: 28, name: "ALLURE HOMME SPORT", brand: "CHANEL" },
    { id: 30, name: "AMBER ROMANCE", brand: "VICTORIA'S SECRET" },
    { id: 31, name: "AMBRE NUIT", brand: "CHRISTIAN DIOR" },
    { id: 35, name: "ANGEL", brand: "VICTORIA'S SECRET" },
    { id: 36, name: "ANGEL MUSE", brand: "MUGLER" },
    { id: 37, name: "ANGEL'S SHARE", brand: "KILIAN" },
    { id: 39, name: "AQUA CELESTIA", brand: "MAISON FRANCIS KURKDJIAN" },
    { id: 44, name: "ARMANI CODE", brand: "GIORGIO ARMANI" },
    { id: 45, name: "ARMANI CODE CASHMERE", brand: "GIORGIO ARMANI" },
    { id: 49, name: "ATOMIC ROSE", brand: "INITIO PARFUMS PRIVES" },
    { id: 50, name: "ATTAPE", brand: "AL REHAB" },
    { id: 53, name: "AU HASARD", brand: "LOUIS VUITTON" },
    { id: 54, name: "AVENTUS", brand: "CREED" },
    { id: 55, name: "AXE AFRICA", brand: "AXE" },
    { id: 60, name: "AZZARO CHROME", brand: "AZZARO" },
    { id: 62, name: "AZZARO SPORT", brand: "AZZARO" },
    { id: 63, name: "AZZARO WANTED", brand: "AZZARO" },
    { id: 66, name: "BABY CAT", brand: "YVES SAINT LAURENT" },
    { id: 67, name: "BACCARAT ROUGE 540", brand: "MAISON FRANCIS KURKDJIAN" },
    { id: 69, name: "BAD BOYS ARE NO GOOD", brand: "KILIAN" },
    { id: 76, name: "BE GIVENCHY", brand: "GIVENCHY" },
    { id: 77, name: "BE DELICIOUS", brand: "DKNY" },
    { id: 82, name: "BITTER PEACH", brand: "TOM FORD" },
    { id: 83, name: "BLACK OPIUM", brand: "YVES SAINT LAURENT" },
    { id: 84, name: "BLACK ORCHID", brand: "TOM FORD" },
    { id: 85, name: "BLACK XS", brand: "PACO RABANNE" },
    { id: 86, name: "BLACK PHANTOM", brand: "KILIAN" },
    { id: 89, name: "BLEU DE CHANEL", brand: "CHANEL" },
    { id: 100, name: "BOMBSHELL", brand: "VICTORIA'S SECRET" },
    { id: 101, name: "BON BON", brand: "VIKTOR & ROLF" },
    { id: 104, name: "BOSS BOTTLED PACIFIC", brand: "HUGO BOSS" },
    { id: 105, name: "BOSS BOTTLED NIGHT", brand: "HUGO BOSS" },
    { id: 106, name: "BOSS ELEMENTS", brand: "HUGO BOSS" },
    { id: 109, name: "BOSS OUD", brand: "HUGO BOSS" },
    { id: 110, name: "BOSS THE SCENT", brand: "HUGO BOSS" },
    { id: 114, name: "BURBERRY GODDESS", brand: "BURBERRY" },
    { id: 116, name: "BURBERRY HER", brand: "BURBERRY" },
    { id: 118, name: "BURBERRY LONDON", brand: "BURBERRY" },
    { id: 120, name: "BURBERRY WEEKEND", brand: "BURBERRY" },
    { id: 121, name: "BVLGARI BLV", brand: "BVLGARI" },
    { id: 122, name: "BVLGARI JASMINE NOIR", brand: "BVLGARI" },
    { id: 123, name: "BVLGARI MAN", brand: "BVLGARI" },
    { id: 128, name: "BVLGARI TYGER", brand: "BVLGARI" },
    { id: 132, name: "CALIFORNIA DREAM", brand: "LOUIS VUITTON" },
    { id: 135, name: "CHANEL NO. 5", brand: "CHANEL" },
    { id: 136, name: "CHANCE", brand: "CHANEL" },
    { id: 139, name: "CHAMPAGNE TOAST", brand: "BATH & BODY WORKS" },
    { id: 140, name: "CHAMPION", brand: "DAVIDOFF" },
    { id: 147, name: "CIGAR", brand: "REMY LATOUR" },
    { id: 148, name: "CITY OF STARS", brand: "LOUIS VUITTON" },
    { id: 149, name: "CK ONE", brand: "CALVIN KLEIN" },
    { id: 152, name: "CLASSIQUE", brand: "JEAN PAUL GAULTIER" },
    { id: 156, name: "CLUB DE NUIT INTENSE", brand: "ARMAF" },
    { id: 157, name: "COACH", brand: "COACH" },
    { id: 158, name: "COFFEE BREAK", brand: "MAISON MARTIN MARGIELA" },
    { id: 160, name: "COOL WATER", brand: "DAVIDOFF" },
    { id: 167, name: "COCO MADEMOISELLE", brand: "CHANEL" },
    { id: 171, name: "CREED AVENTUS", brand: "CREED" },
    { id: 172, name: "CUIR MUSK", brand: "AJMAL" },
    { id: 174, name: "D&G THE ONE MAN", brand: "DOLCE & GABBANA" },
    { id: 176, name: "D&G LIGHT BLUE", brand: "DOLCE & GABBANA" },
    { id: 179, name: "DAISY", brand: "MARC JACOBS" },
    { id: 180, name: "DAISY BLUE", brand: "MARC JACOBS" },
    { id: 186, name: "DAVID BECKHAM INSTINCT", brand: "DAVID BECKHAM" },
    { id: 191, name: "DIESEL BAD", brand: "DIESEL" },
    { id: 193, name: "DIOR ADDICT 2", brand: "CHRISTIAN DIOR" },
    { id: 194, name: "DIOR HOMME SPORT", brand: "CHRISTIAN DIOR" },
    { id: 202, name: "DUNHILL CUSTOM", brand: "ALFRED DUNHILL" },
    { id: 203, name: "DUNHILL DESIRE", brand: "ALFRED DUNHILL" },
    { id: 210, name: "EILISH", brand: "BILLIE EILISH" },
    { id: 213, name: "ELYSIUM POUR HOMME", brand: "ROJA DOVE" },
    { id: 214, name: "ENGLISH PEAR AND FREESIA", brand: "JO MALONE LONDON" },
    { id: 216, name: "ERBA PURA", brand: "SOSPIRO" },
    { id: 221, name: "ESCAPE FOR MAN", brand: "CALVIN KLEIN" },
    { id: 223, name: "ETERNITY FOR MAN", brand: "CALVIN KLEIN" },
    { id: 226, name: "EUPHORIA", brand: "CALVIN KLEIN" },
    { id: 230, name: "FAHRENHEIT", brand: "CHRISTIAN DIOR" },
    { id: 238, name: "FERRARI RED", brand: "FERRARI" },
    { id: 240, name: "FIFTH AVENUE", brand: "ELIZABETH ARDEN" },
    { id: 254, name: "FORBIDDEN GAMES", brand: "KILIAN" },
    { id: 258, name: "FUCKING FABULOUS", brand: "TOM FORD" },
    { id: 261, name: "GENTLEMAN", brand: "GIVENCHY" },
    { id: 263, name: "GODFATHER", brand: "BYREDO" },
    { id: 268, name: "GOOD GIRL", brand: "CAROLINA HERRERA" },
    { id: 270, name: "GREY VETIVER", brand: "TOM FORD" },
    { id: 273, name: "GUCCI BY GUCCI", brand: "GUCCI" },
    { id: 274, name: "GUCCI BLOOM", brand: "GUCCI" },
    { id: 275, name: "GUCCI FLORA", brand: "GUCCI" },
    { id: 279, name: "GUCCI GUILTY MAN", brand: "GUCCI" },
    { id: 285, name: "HALFETI", brand: "PENHALIGON" },
    { id: 297, name: "HOT WATER", brand: "DAVIDOFF" },
    { id: 298, name: "HUGO BOSS DARK BLUE", brand: "HUGO BOSS" },
    { id: 300, name: "HUGO BOSS MAN", brand: "HUGO BOSS" },
    { id: 307, name: "HYPNOTIC POISON", brand: "CHRISTIAN DIOR" },
    { id: 308, name: "ISSEY MIYAKE MEN", brand: "ISSEY MIYAKE" },
    { id: 310, name: "IMAGINATION", brand: "LOUIS VUITTON" },
    { id: 314, name: "INTERLUDE MAN", brand: "AMOUAGE" },
    { id: 315, name: "INVICTUS", brand: "PACO RABANNE" },
    { id: 319, name: "J'ADORE", brand: "CHRISTIAN DIOR" },
    { id: 326, name: "JAZZ CLUB", brand: "MAISON MARTIN MARGIELA" },
    { id: 327, name: "JIMMY CHOO MAN", brand: "JIMMY CHOO" },
    { id: 332, name: "JUNGLE", brand: "KENZO" },
    { id: 336, name: "KAYALI VANILLA", brand: "KAYALI FRAGRANCES" },
    { id: 342, name: "KOUROS", brand: "YVES SAINT LAURENT" },
    { id: 345, name: "LACOSTE BLUE", brand: "LACOSTE" },
    { id: 346, name: "LACOSTE RED", brand: "LACOSTE" },
    { id: 347, name: "LACOSTE WHITE", brand: "LACOSTE" },
    { id: 349, name: "LADY MILLION", brand: "PACO RABANNE" },
    { id: 351, name: "LA NUIT DE L'HOMME", brand: "YVES SAINT LAURENT" },
    { id: 352, name: "LA VIE EST BELLE", brand: "LANCOME" },
    { id: 356, name: "LE MALE", brand: "JEAN PAUL GAULTIER" },
    { id: 359, name: "L'HOMME YSL", brand: "YVES SAINT LAURENT" },
    { id: 361, name: "LIBRE YSL", brand: "YVES SAINT LAURENT" },
    { id: 364, name: "LIME BASIL & MANDARIN", brand: "JO MALONE LONDON" },
    { id: 368, name: "LOST CHERRY", brand: "TOM FORD" },
    { id: 370, name: "LOVE DON'T BE SHY", brand: "KILIAN" },
    { id: 382, name: "MATIERE NOIRE", brand: "LOUIS VUITTON" },
    { id: 384, name: "MICHAEL KORS", brand: "MICHAEL KORS" },
    { id: 385, name: "MISS DIOR BLOOMING BOUQUET", brand: "CHRISTIAN DIOR" },
    { id: 391, name: "MONTBLANC EXPLORER", brand: "MONTBLANC" },
    { id: 392, name: "MONTBLANC LEGEND", brand: "MONTBLANC" },
    { id: 394, name: "MOJAVE GHOST", brand: "BYREDO" },
    { id: 410, name: "MYRRH AND TONKA", brand: "JO MALONE LONDON" },
    { id: 413, name: "NAUTICA BLUE", brand: "NAUTICA" },
    { id: 414, name: "NAUTICA VOYAGE", brand: "NAUTICA" },
    { id: 422, name: "NOIR DE NOIR", brand: "TOM FORD" },
    { id: 423, name: "NOIR EXTREME", brand: "TOM FORD" },
    { id: 425, name: "OMBRE LEATHER", brand: "TOM FORD" },
    { id: 429, name: "ONE MILLION ELIXIR", brand: "PACO RABANNE" },
    { id: 430, name: "ONE MILLION LUCKY", brand: "PACO RABANNE" },
    { id: 431, name: "ONLY THE BRAVE", brand: "DIESEL" },
    { id: 444, name: "OUD ASSAM", brand: "MAISON ANTHONY MARMIN" },
    { id: 449, name: "OUD ISPAHAN", brand: "CHRISTIAN DIOR" },
    { id: 457, name: "OUD WHITE", brand: "TOM FORD" },
    { id: 458, name: "OUD WOOD", brand: "TOM FORD" },
    { id: 461, name: "PARIS HILTON MAN", brand: "PARIS HILTON" },
    { id: 465, name: "PEGASUS", brand: "PARFUMS DE MARLY" },
    { id: 467, name: "PERRY ELLIS MAN", brand: "PERRY ELLIS" },
    { id: 472, name: "PLEASURE EXOTIC", brand: "ESTEE LAUDER" },
    { id: 476, name: "POLO BLACK", brand: "RALPH LAUREN" },
    { id: 477, name: "POLO BLUE", brand: "RALPH LAUREN" },
    { id: 478, name: "POLO GREEN", brand: "RALPH LAUREN" },
    { id: 479, name: "POLO RED", brand: "RALPH LAUREN" },
    { id: 481, name: "POISON GIRL", brand: "CHRISTIAN DIOR" },
    { id: 484, name: "PORTRAIT OF A LADY", brand: "FREDERIC MALLE" },
    { id: 485, name: "PRADA CANDY", brand: "PRADA" },
    { id: 486, name: "PRADA LUNA ROSSA", brand: "PRADA" },
    { id: 493, name: "PURE XS", brand: "PACO RABANNE" },
    { id: 504, name: "RICCI RICCI", brand: "NINA RICCI" },
    { id: 506, name: "ROMANCE", brand: "RALPH LAUREN" },
    { id: 512, name: "RUSH", brand: "GUCCI" },
    { id: 518, name: "SAUVAGE", brand: "CHRISTIAN DIOR" },
    { id: 519, name: "SAUVAGE ELIXIR", brand: "CHRISTIAN DIOR" },
    { id: 520, name: "SCANDAL JPG", brand: "JEAN PAUL GAULTIER" },
    { id: 523, name: "SHALIMAR", brand: "GUERLAIN" },
    { id: 532, name: "SICILY", brand: "DOLCE & GABBANA" },
    { id: 538, name: "SILVER SHADOW", brand: "DAVIDOFF" },
    { id: 541, name: "SPICEBOMB", brand: "VIKTOR & ROLF" },
    { id: 542, name: "SPICEBOMB EXTREME", brand: "VIKTOR & ROLF" },
    { id: 544, name: "STRONGER WITH YOU", brand: "GIORGIO ARMANI" },
    { id: 556, name: "TENDRE POISON", brand: "CHRISTIAN DIOR" },
    { id: 559, name: "TERRE D'HERMES", brand: "HERMES" },
    { id: 560, name: "THE ONE WOMAN", brand: "DOLCE & GABBANA" },
    { id: 563, name: "TOBACCO OUD", brand: "TOM FORD" },
    { id: 564, name: "TOBACCO VANILLE", brand: "TOM FORD" },
    { id: 565, name: "TOMMY BOY", brand: "TOMMY HILFIGER" },
    { id: 566, name: "TOMMY GIRL", brand: "TOMMY HILFIGER" },
    { id: 572, name: "TUSCAN LEATHER", brand: "TOM FORD" },
    { id: 576, name: "VALENTINO UOMO BORN IN ROMA", brand: "VALENTINO" },
    { id: 582, name: "VELVET ORCHID", brand: "TOM FORD" },
    { id: 583, name: "VERSACE BRIGHT CRYSTAL", brand: "VERSACE" },
    { id: 584, name: "VERSACE DYLAN BLUE", brand: "VERSACE" },
    { id: 586, name: "VERSACE EROS FLAME", brand: "VERSACE" },
    { id: 587, name: "VERSACE POUR HOMME", brand: "VERSACE" },
    { id: 590, name: "VERY SEXY FOR HER", brand: "VICTORIA'S SECRET" },
    { id: 593, name: "VINTAGE", brand: "JOHN VARVATOS" },
    { id: 597, name: "WARM VANILLA SUGAR", brand: "BATH & BODY WORKS" },
    { id: 602, name: "WHISKY SMOKE", brand: "BEARDO" },
    { id: 604, name: "YSL Y", brand: "YVES SAINT LAURENT" },
    { id: 605, name: "ZINO DAVIDOFF FOR MAN", brand: "DAVIDOFF" }
  ];